POST http://localhost:8000/create-mentor
Content-Type: application/json

{
    "name":"Djole",
    "email":"kocic19899@gmail.com",
    "user":{
        "email":"djordje@nueralabs.com",
        "accepted":false,
        "_id":"65b8fc4aa9a17d0870246fca"
    }
}