POST http://localhost:8000/create-mentor
Content-Type: application/json

{
    "name":"Djole",
    "email":"kocic19899@gmail.com",
    "user":{
        "email":"mr.milosa@gmail.com",
        "accepted":false,
        "_id":"65ca2067824de6718e3f13ff"
    }
}