POST http://localhost:8000/create-mentor
Content-Type: application/json

{
    "name":"Djole",
    "email":"djordje@nueralabs.com",
    "user":{
        "email":"acengen19899@gmail.com",
        "_id":"65bfbe429e9cd7bea657187f"
    }
}