@id = 65bfbe429e9cd7bea657187f
PUT http://localhost:8000/update-user/{{id}}
Content-Type: application/json

{
    "consumptionInfo":{
        "cigarettesAvoided": 0,
        "cigarettesAvoidedCost":0
    }
}